A2HOSTING:
  hostname: 185.146.22.233
  identityFile: '~/.ssh/a2hosting'
  deploy_path: '~/'
  remote_user: 'booksban'
  user: 'booksban'
  port: 7822
  http_user: 'booksban'
  stage: production
  forwardAgent: true
  multiplexing: false
  ssh_multiplexing: false
  git_tty: false
  branch: 'main'
# IONOS:
#   hostname: 'home583749822.1and1-data.host'
#   deploy_path: '~/'
#   remote_user: 'u81549941'
#   passsword: 'xfLuRZDaI5CHZM6oDwiq!^'
#   user: 'u81549941'
#   port: 22
#   http_user: 'u81549941'
#   stage: production
#   forwardAgent: true
#   multiplexing: false
#   ssh_multiplexing: false
#   git_tty: false
#   branch: 'deployer'
  